modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "regeneration"
version = "${version}"
displayName = "Example Mod"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.regeneration]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.regeneration]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
